package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/weeb-vip/notifications-service/graph/generated"
	"github.com/weeb-vip/notifications-service/graph/model"
	"github.com/weeb-vip/notifications-service/internal/resolvers"
)

// FindActivityByID is the resolver for the findActivityByID field.
func (r *entityResolver) FindActivityByID(ctx context.Context, id string) (*model.Activity, error) {
	return resolvers.ActivityByID(ctx, r.FeedService, id)
}

// FindNotificationByID is the resolver for the findNotificationByID field.
func (r *entityResolver) FindNotificationByID(ctx context.Context, id string) (*model.Notification, error) {
	// Nothing references Notification from another subgraph; an inbox is
	// private to its owner and read only through the viewer-scoped queries.
	return nil, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
