package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/weeb-vip/notifications-service/graph/generated"
	"github.com/weeb-vip/notifications-service/graph/model"
	"github.com/weeb-vip/notifications-service/internal/resolvers"
)

// MarkNotificationsRead is the resolver for the markNotificationsRead field.
func (r *mutationResolver) MarkNotificationsRead(ctx context.Context, ids []string) (bool, error) {
	return resolvers.MarkNotificationsRead(ctx, r.NotificationsService, ids)
}

// MarkAllNotificationsRead is the resolver for the markAllNotificationsRead field.
func (r *mutationResolver) MarkAllNotificationsRead(ctx context.Context) (bool, error) {
	return resolvers.MarkAllNotificationsRead(ctx, r.NotificationsService)
}

// UpdateNotificationPreference is the resolver for the updateNotificationPreference field.
func (r *mutationResolver) UpdateNotificationPreference(ctx context.Context, typeArg model.NotificationType, channel model.NotificationChannel, enabled bool) (*model.NotificationPreference, error) {
	return resolvers.UpdateNotificationPreference(ctx, r.NotificationsService, typeArg, channel, enabled)
}

// RegisterPushSubscription is the resolver for the registerPushSubscription field.
func (r *mutationResolver) RegisterPushSubscription(ctx context.Context, input model.PushSubscriptionInput) (*model.PushSubscription, error) {
	return resolvers.RegisterPushSubscription(ctx, r.NotificationsService, input)
}

// UnregisterPushSubscription is the resolver for the unregisterPushSubscription field.
func (r *mutationResolver) UnregisterPushSubscription(ctx context.Context, endpoint string) (bool, error) {
	return resolvers.UnregisterPushSubscription(ctx, r.NotificationsService, endpoint)
}

// Feed is the resolver for the feed field.
func (r *queryResolver) Feed(ctx context.Context, page int, limit int) (*model.ActivityPaginated, error) {
	return resolvers.Feed(ctx, r.FeedService, page, limit)
}

// UserActivity is the resolver for the userActivity field.
func (r *queryResolver) UserActivity(ctx context.Context, userID string, page int, limit int) (*model.ActivityPaginated, error) {
	return resolvers.UserActivity(ctx, r.FeedService, userID, page, limit)
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, page int, limit int, unreadOnly *bool) (*model.NotificationPaginated, error) {
	return resolvers.Notifications(ctx, r.NotificationsService, page, limit, unreadOnly)
}

// UnreadNotificationCount is the resolver for the unreadNotificationCount field.
func (r *queryResolver) UnreadNotificationCount(ctx context.Context) (int, error) {
	return resolvers.UnreadNotificationCount(ctx, r.NotificationsService)
}

// NotificationPreferences is the resolver for the notificationPreferences field.
func (r *queryResolver) NotificationPreferences(ctx context.Context) ([]*model.NotificationPreference, error) {
	return resolvers.NotificationPreferences(ctx, r.NotificationsService)
}

// PushSubscriptions is the resolver for the pushSubscriptions field.
func (r *queryResolver) PushSubscriptions(ctx context.Context) ([]*model.PushSubscription, error) {
	return resolvers.PushSubscriptions(ctx, r.NotificationsService)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
