// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

// Something a user did to one of their lists, as shown in a feed.
//
// The service stores ids only. actor, anime and work are resolved by their
// owning subgraphs through the router, so this type never goes stale when a
// username or a title changes.
type Activity struct {
	ID    string       `json:"id"`
	Type  ActivityType `json:"type"`
	Actor *PublicUser  `json:"actor"`
	Anime *Anime       `json:"anime,omitempty"`
	Work  *Work        `json:"work,omitempty"`
	// The list status after the change, in the owning service's vocabulary.
	Status *string `json:"status,omitempty"`
	// Set for status changes: the status before.
	PreviousStatus *string  `json:"previousStatus,omitempty"`
	Score          *float64 `json:"score,omitempty"`
	OccurredAt     string   `json:"occurredAt"`
}

func (Activity) IsEntity() {}

type ActivityPaginated struct {
	Page       int         `json:"page"`
	Limit      int         `json:"limit"`
	Total      int         `json:"total"`
	Activities []*Activity `json:"activities"`
}

type Mutation struct {
}

// One item in a user's inbox.
type Notification struct {
	ID   string           `json:"id"`
	Type NotificationType `json:"type"`
	// Who caused it, when someone did.
	Actor *PublicUser `json:"actor,omitempty"`
	// The activity it is about, when it is about one.
	Activity *Activity `json:"activity,omitempty"`
	// Type-specific details, as a JSON document.
	Payload   *string `json:"payload,omitempty"`
	ReadAt    *string `json:"readAt,omitempty"`
	CreatedAt string  `json:"createdAt"`
}

func (Notification) IsEntity() {}

type NotificationPaginated struct {
	Page          int             `json:"page"`
	Limit         int             `json:"limit"`
	Total         int             `json:"total"`
	Notifications []*Notification `json:"notifications"`
}

type NotificationPreference struct {
	Type    NotificationType    `json:"type"`
	Channel NotificationChannel `json:"channel"`
	Enabled bool                `json:"enabled"`
}

type PushSubscription struct {
	ID        string       `json:"id"`
	Platform  PushPlatform `json:"platform"`
	Endpoint  string       `json:"endpoint"`
	CreatedAt string       `json:"createdAt"`
}

type PushSubscriptionInput struct {
	Platform PushPlatform `json:"platform"`
	// Web Push endpoint URL, or the FCM/APNs device token.
	Endpoint string `json:"endpoint"`
	// Web Push only: the subscription's P-256 public key.
	P256dh *string `json:"p256dh,omitempty"`
	// Web Push only: the subscription's auth secret.
	Auth      *string `json:"auth,omitempty"`
	UserAgent *string `json:"userAgent,omitempty"`
}

type Query struct {
}

type ActivityType string

const (
	ActivityTypeAnimeAdded         ActivityType = "ANIME_ADDED"
	ActivityTypeAnimeStatusChanged ActivityType = "ANIME_STATUS_CHANGED"
	ActivityTypeAnimeScored        ActivityType = "ANIME_SCORED"
	ActivityTypeWorkAdded          ActivityType = "WORK_ADDED"
	ActivityTypeWorkStatusChanged  ActivityType = "WORK_STATUS_CHANGED"
	ActivityTypeWorkScored         ActivityType = "WORK_SCORED"
)

var AllActivityType = []ActivityType{
	ActivityTypeAnimeAdded,
	ActivityTypeAnimeStatusChanged,
	ActivityTypeAnimeScored,
	ActivityTypeWorkAdded,
	ActivityTypeWorkStatusChanged,
	ActivityTypeWorkScored,
}

func (e ActivityType) IsValid() bool {
	switch e {
	case ActivityTypeAnimeAdded, ActivityTypeAnimeStatusChanged, ActivityTypeAnimeScored, ActivityTypeWorkAdded, ActivityTypeWorkStatusChanged, ActivityTypeWorkScored:
		return true
	}
	return false
}

func (e ActivityType) String() string {
	return string(e)
}

func (e *ActivityType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActivityType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActivityType", str)
	}
	return nil
}

func (e ActivityType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActivityType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActivityType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NotificationChannel string

const (
	NotificationChannelInApp NotificationChannel = "IN_APP"
	NotificationChannelPush  NotificationChannel = "PUSH"
	NotificationChannelEmail NotificationChannel = "EMAIL"
)

var AllNotificationChannel = []NotificationChannel{
	NotificationChannelInApp,
	NotificationChannelPush,
	NotificationChannelEmail,
}

func (e NotificationChannel) IsValid() bool {
	switch e {
	case NotificationChannelInApp, NotificationChannelPush, NotificationChannelEmail:
		return true
	}
	return false
}

func (e NotificationChannel) String() string {
	return string(e)
}

func (e *NotificationChannel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NotificationChannel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NotificationChannel", str)
	}
	return nil
}

func (e NotificationChannel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NotificationChannel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NotificationChannel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NotificationType string

const (
	// Someone asked to follow the viewer, who requires approval.
	NotificationTypeFollowRequested NotificationType = "FOLLOW_REQUESTED"
	// A user the viewer asked to follow approved the request.
	NotificationTypeFollowAccepted NotificationType = "FOLLOW_ACCEPTED"
	// Someone started following the viewer.
	NotificationTypeNewFollower NotificationType = "NEW_FOLLOWER"
)

var AllNotificationType = []NotificationType{
	NotificationTypeFollowRequested,
	NotificationTypeFollowAccepted,
	NotificationTypeNewFollower,
}

func (e NotificationType) IsValid() bool {
	switch e {
	case NotificationTypeFollowRequested, NotificationTypeFollowAccepted, NotificationTypeNewFollower:
		return true
	}
	return false
}

func (e NotificationType) String() string {
	return string(e)
}

func (e *NotificationType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NotificationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NotificationType", str)
	}
	return nil
}

func (e NotificationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NotificationType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NotificationType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PushPlatform string

const (
	PushPlatformWeb     PushPlatform = "WEB"
	PushPlatformIos     PushPlatform = "IOS"
	PushPlatformAndroid PushPlatform = "ANDROID"
)

var AllPushPlatform = []PushPlatform{
	PushPlatformWeb,
	PushPlatformIos,
	PushPlatformAndroid,
}

func (e PushPlatform) IsValid() bool {
	switch e {
	case PushPlatformWeb, PushPlatformIos, PushPlatformAndroid:
		return true
	}
	return false
}

func (e PushPlatform) String() string {
	return string(e)
}

func (e *PushPlatform) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PushPlatform(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PushPlatform", str)
	}
	return nil
}

func (e PushPlatform) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PushPlatform) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PushPlatform) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
